version: '3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=joomla
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  joomla:
    image: joomla:php7.4-apache
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=$MYSQL_USER
      - JOOMLA_DB_PASSWORD=$MYSQL_PASSWORD
    networks:
      - app-network
    volumes:
      - ./log:/var/log/apache2


networks:
  app-network:
    driver: bridge
