#!/usr/bin/env tarantool
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kirill.
--- DateTime: 4/2/21 8:14 PM
---


local clock = require('clock')
local fio = require('fio')
local hostname = require('popen').shell('hostname','r')
local port = tonumber(arg[1])
local login = tostring(arg[2])
local password = tostring(arg[3])

local host = hostname:read():rstrip()
hostname:close()

if #arg < 3 then
    error("Usage: tarantool -i server.lua <port> <username> <password>")
end
if port == nil then
    error('Invalid port')
end

local work_dir = fio.pathjoin('data', port)
fio.mktree(work_dir)
box.cfg({
    listen = port,	
    work_dir = work_dir,
})
box.schema.user.passwd(login, password)

local requests_timestamps = {}

local function stats()
    local current_time = clock.monotonic64()
    table.insert(requests_timestamps, current_time)
    while #requests_timestamps ~= 0 and current_time - requests_timestamps[1] > 1e9 do
        table.remove(requests_timestamps, 1)
    end 
    local host_stats = host..':'..port..': '..#requests_timestamps
    return host_stats
end

function exec()
    return stats()
end