---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kirill.
--- DateTime: 4/2/21 8:14 PM
---

#!/usr/bin/env tarantool

local fio = require('fio')
local digest = require('digest')
local port = tonumber(arg[1])
if port == nil then
    error('Invalid port')
end

local work_dir = fio.pathjoin('data', port)
fio.mktree(work_dir)
box.cfg({
    listen = port,
    work_dir = work_dir,
})
box.schema.user.passwd('admin', 'test')

function exec()
    local str = string.format("I'm %s", port)
    for _ = 1, 1e2 do
        digest.sha512_hex(str)
    end
    return str
end