#!/usr/bin/env tarantool
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kirill Kopylov.
--- DateTime: 3/24/21 7:56 PM
---
---
---
local fio = require('fio')
local yaml = require('yaml')
local json = require('json')
local urlencode = require('urlencode')
local client = require('http.client').new()

box.cfg {
   background = true,
   log = '1.log',
   pid_file = '1.pid'
}

local function proxy(req)
    local req_headers = req:headers()
    local method = req:method()
    local uri_params=""
    if method == "POST" or method == "PUT" then
        req_headers['content-length']=nil
        if req_headers['content-type'] == 'application/x-www-form-urlencoded' then
            uri_params=urlencode.table(req:param())
        end
        if req_headers['content-type'] == 'application/json' then
            uri_params=json.encode(req:param())
        end
    end
    local resp = client:request(method,proxy_host..":"..proxy_port..req:path().."?"..req:query(),uri_params,
            {headers=req_headers,follow_location=false, verbose=true, max_header_name_len=128, accept_encoding=true})
    resp.headers["transfer-encoding"] = nil
    resp.headers["server"] = nil
    return {
        status = resp.status,
        body = resp.body,
        headers = resp.headers
    }
end

if fio.path.is_file("proxy.yml") then
    config_file = fio.open("proxy.yml")
else
    os.exit(1)
end

yaml_buffer = config_file:read()
config_file:close()
config=yaml.decode(yaml_buffer)

port = config["proxy"]["port"]
proxy_host = config["proxy"]["bypass"]["host"]
proxy_port = config["proxy"]["bypass"]["port"]

local router = require('http.router').new()
router:route({ method = 'ANY', path = '/(.*)' }, proxy)
router:route({ method = 'ANY', path = '/' }, proxy)

local server = require('http.server').new('localhost', port)
server:set_router(router)
server:start()
